### ISSUE TITLE
Replace JObject.Load by JToken.Load in JsonKeyValueParser.Parse(KeyValue)

### ISSUE THREAD

**Issue by Hunter21007** [Drawaes/CondenserDotNet#25]
Actually the only way to provide configuration to Condenser is as a Json Object like

```
{
      "Key": "Value"
}
```

if i try to create a config object which is an array:

```
[
    {
         "key":"value1"
    },
    {
          "key":"value2"
    }
]
```

I get an exception like: `Current JsonReader item is not an object: StartArray. Path '', line 1, position 2.`

I have changed behavior of the JsonKeyValueParser in the Function Parse:

```
diff --git a/src/CondenserDotNet.Client/Configuration/JsonKeyValueParser.cs b/src/CondenserDotNet.Client/Configuration/JsonKeyValueParser.cs
index 4b4935d..d528995 100644
--- a/src/CondenserDotNet.Client/Configuration/JsonKeyValueParser.cs
+++ b/src/CondenserDotNet.Client/Configuration/JsonKeyValueParser.cs
@@ -30,10 +30,10 @@ namespace CondenserDotNet.Client.Configuration
             {
                 DateParseHandling = DateParseHandling.None
             };
+            
+            var jsonConfig = JToken.Load(_reader);
 
-            var jsonConfig = JObject.Load(_reader);
-
-            VisitJObject(jsonConfig);
+            VisitToken(jsonConfig);
 
             foreach (var kv in _data)
                 yield return new KeyValue
```

Now everything is OK

(Sorry i am lazy to make a PR :) )

**Comment by Drawaes** [comment]
cc @deanshackley

**Comment by deanshackley** [comment]
Thanks for this, we will make this update.  Regarding that this is the only way to add configuration.  You do have options.  You can add keys in consul as normal keys.  So for example 

Org/Settings/Key1 = "123"
Org/Settings/Key2 = "456"

Then just use the AddConsul extension on the configuration builder.  Instead of the add Json.  You can then still bind this to an object like 

Settings
{
 Key1,
Key2
}

Using the configure or configurereloadable.  

Alternatively, you can inject the IConfiguration into your controller directly and simply call GetValue("key") on it to get the value.  You need to register this first in the configure services sections as follows

services.AddSingleton(Configuration);

We are in the process of updating the documentation and samples to reflect these choices.

Thanks

**Comment by Hunter21007** [comment]
Yes, thanks. But my use case is as following:

`my/config/section/objectlist`

```
[
{
name:name1
setting:setting1
another:ankther1
},
{
name:name2
setting:setting2
another:ankther2
},
{....}
]
```

```
_serviceManager.Config.AddReloadable("my/config/section");
var objList = _conf.GetSection("object list").Get<List<MyObject>>();
```

Or `public MyController(IOptions<List<MyObject>> objList) {....`

**Comment by Drawaes** [comment]
#26

**Comment by Drawaes** [comment]
It's now merged. When you get time can you check and if you are happy, close the issue.

**Comment by Hunter21007** [comment]
Hi, is it possible to build nightly? It is still 197.
Thanks.

Jurij Zahn
Sent from mobile device

Am 16.12.2016 13:12 schrieb "Tim Seaward" <notifications@github.com>:

**Comment by Drawaes** [comment]
It should be building now. It does it from the merge. I will check

**Comment by Drawaes** [comment]
You were just too quick :) should be 199

**Comment by Hunter21007** [comment]
Sorry for that :)
Will Check it asap (i am actually sick)

Jurij Zahn
Sent from mobile device

Am 16.12.2016 13:17 schrieb "Tim Seaward" <notifications@github.com>:

**Comment by Drawaes** [comment]
No problems, the quick feedback is good. You are just quicker than appveyor could build

**Comment by Hunter21007** [comment]
Works as expected with 0.6.1-199
Thanks!
